### ISSUE TITLE
Error occurred in Node v7.5.0 "Cannot find module 'internal/fs'"

### ISSUE THREAD

**Issue by esnya** [ukatama/presentation-timer#9]
> gulp test

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (C:\Users\ukatama\Documents\ukatama\presentation-timer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by esnya** [comment]
リポジトリをアーカイブする前の未処理 issue 整理として閉じます。必要になった場合は現行のメンテナンス対象で改めて扱います。
